name: Secrets scan

permissions:
  contents: read
  pull-requests: read

on:
  workflow_call:
    secrets:
      NHSAPP_GITLEAKS_LICENSE:
        description: 'A Gitleaks license passed from the caller workflow'
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.NHSAPP_GITLEAKS_LICENSE }}
