name: Gitleaks scan

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    uses: ./.github/workflows/gitleaks_secret_scan.yml
    secrets:
      NHSAPP_GITLEAKS_LICENSE: ${{ secrets.NHSAPP_GITLEAKS_LICENSE }}
